services:
  api:
    image: beatrizruiz981/api-featurehub:latest 
    restart: always
    depends_on:
      - db
    env_file: 
    - ".env"
    ports:
      - "192.168.1.130:8000:8000" # <IP:port_local>:<port_container>
  db:
    image: postgres:16 # AÃ±adir version para evitar problemas de compatibilidad
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres-db:/var/lib/postgresql/data
  frontend:
    image: beatrizruiz981/nginx-front-featurehub:latest
    ports:
      - "80:80"
    depends_on:
      - api

volumes:
  postgres-db: